export const  links = {
    resumeLink: "https://github.com/nileshnwani/Resume/blob/a022bc67d09c4a08a665ce06171f530ad4b72e71/Nilesh%20Wani%20Resume1.pdf",
    githubLink:"https://github.com/nileshnwani",
    linkedinLink: "https://www.linkedin.com/in/nilesh-wani-7a7053241",
    youtubeLink:"",
    twitterLink: "",
    instagramLink:"https://www.instagram.com/nileshnw/?igsh=MXR3ZjMybXJudTZ6OA%3D%3D#",
    facebookLink:"",
    gmailLink:"mailto:nileshwani21099@gmail.com",
}
export const skillImage={
    c:"https://img.icons8.com/color/48/000000/c-programming.png",
    cpp:"https://img.icons8.com/color/48/c-plus-plus-logo.png",
    js:"https://img.icons8.com/color/48/javascript--v1.png",
    python:"https://img.icons8.com/color/48/000000/python--v1.png",
    mysql:"https://img.icons8.com/color/60/000000/mysql-logo.png",
    mongodb:"https://img.icons8.com/color/48/000000/mongodb.png",
    oracle:"https://img.icons8.com/color/48/oracle-logo.png",
    postgres:"https://img.icons8.com/color/48/postgreesql.png",
    css:"https://img.icons8.com/color/48/000000/css3.png",
    html:"https://img.icons8.com/color/48/000000/html-5--v1.png",
    javascript:"https://img.icons8.com/color/48/000000/javascript--v1.png",
    react:"https://img.icons8.com/ultraviolet/48/000000/react--v1.png",
    php:"https://img.icons8.com/color/50/php.png",
    sublime:"https://img.icons8.com/color/50/sublime-text.png",
    vscode:"https://img.icons8.com/color/48/000000/visual-studio-code-2019.png",
    eclipse:"https://img.icons8.com/office/40/null/java-eclipse.png",
    node:"https://img.icons8.com/color/48/000000/nodejs.png",
    bootstrap:"https://img.icons8.com/color/48/000000/bootstrap.png",
    django:"https://img.icons8.com/color/48/ffffff/django.png",
    flask:"https://img.icons8.com/nolan/64/flask.png",
    express:"https://img.icons8.com/color/50/express-js.png",
    reactnative:"https://img.icons8.com/nolan/64/react-native.png",
    git: "https://img.icons8.com/color/48/000000/git.png",
    android: "https://img.icons8.com/color/48/000000/android-os.png",
    postman: "https://img.icons8.com/external-tal-revivo-color-tal-revivo/48/null/external-postman-is-the-only-complete-api-development-environment-logo-color-tal-revivo.png",
    rest:"https://img.icons8.com/color/48/api-settings.png",
    ml:"https://img.icons8.com/color/48/artificial-intelligence.png",
    dl:"https://img.icons8.com/color/48/brain-3.png",
    ai:"https://img.icons8.com/color/48/chipping.png"
}

